type: order_cards
score: 2
header: Orthonormalization Quiz
text: Order cards to form Gramm-Schmidt Orthonormalization Algorighm
shuffle: true
quiz:
  variants:
    - text: Take the first vector $\mathbf x_1$
    - text: |
        Normalise it and add to the new system of vectors 
        $$\mathbf e_1 = \frac{\mathbf x_1}{|\mathbf x_1|}$$
    - text: |
        Take the next vector $\mathbf x_k$
    - text: |
        Remove from it all colinear components with the vectors that are already
        in the system making the new vector orthogonal to all of them:

        $$\mathbf x_k^* = \mathbf x_k - \sum_{n = 1}^{k-1} \left<\mathbf x_k, \mathbf e_n \right> 
        \mathbf e_n$$
    - text: |
        Normalise the result:
        $$\mathbf e_k = \frac{\mathbf x_k^*}{|\mathbf x_k^*|}$$
    - text: |
        Repeat previous 3 steps for the remaining vectors in the original system
visible: false
